AWSTemplateFormatVersion: "2010-09-09"

Conditions:
  CreateGlueJobBucket: !Not [!Equals [!Ref "AWS::Region", "us-east-1"]]

Resources:
  GlueJobBucket:
    Type: AWS::S3::Bucket
    Condition: CreateGlueJobBucket
    Properties:
      BucketName: project-test-bucket-xyz

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueJobRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [glue.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: GlueJobPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"

  GlueJob:
    Type: AWS::Glue::Job
    DependsOn: GlueJobBucket  # Explicit dependency
    Properties:
      Name: MyPythonShellJob
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: pythonshell
        PythonVersion: "3.9"
        ScriptLocation: !Sub "s3://${GlueJobBucket}/your-python-script.py"
      DefaultArguments:
        "--extra-py-files": !Sub "s3://${GlueJobBucket}/your-dependency.zip"
      MaxRetries: 0
      Timeout: 10
