AWSTemplateFormatVersion: "2010-09-09"

Resources:
  GlueJobBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-bucket

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: MyPythonShellJob
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: pythonshell
        ScriptLocation: !Sub "s3://${GlueJobBucket}/your-python-script.py"
      DefaultArguments:
        "--extra-py-files": !Sub "s3://${GlueJobBucket}/your-dependency.zip"
      Connections:
        Connections: []
      MaxRetries: 0
      Timeout: 10

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueJobRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [glue.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: GlueJobPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: 
                  - !Sub "arn:aws:s3:::${GlueJobBucket}/*"
