name: aws-cloud-infra-pipeline

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Run AWS Cloud Infra Pipeline
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = github.context.payload.ref.split('/').pop();
            if (branch === 'main' || branch === 'dev') {
              const response = await octokit.actions.createWorkflowDispatch({
                owner: 'nick-aws-k',
                repo: 'data_ingestion',
                workflow_id: 'aws-cloud-infra-network-pipeline.yml',
                ref: branch
              });
              console.log(response);
            }
            await runWorkflow('aws-cloud-infra-network-pipeline.yml');
            await runWorkflow('aws-cloud-infra-iam-pipeline.yml');
            await runWorkflow('aws-cloud-infra-s3-pipeline.yml');
            await runWorkflow('aws-cloud-infra-glue-pipeline.yml');
